// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAWRfBpGFUg4cFy7ADnRWB6tREeeEt1oo',
    appId: '1:1022222703700:web:915bb286a6ec9426c6a1c1',
    messagingSenderId: '1022222703700',
    projectId: 'flex-market-cc177',
    authDomain: 'flex-market-cc177.firebaseapp.com',
    storageBucket: 'flex-market-cc177.appspot.com',
    measurementId: 'G-RBET60YJDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFGk9neS9kC4Q8tyUGqqc3QFSVSVcA2vg',
    appId: '1:1022222703700:android:f376d35738aa7a06c6a1c1',
    messagingSenderId: '1022222703700',
    projectId: 'flex-market-cc177',
    storageBucket: 'flex-market-cc177.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQWfTw4tuSWAHdZLnTsSl8mDqPIGZuBEY',
    appId: '1:1022222703700:ios:e78db21aff43dd57c6a1c1',
    messagingSenderId: '1022222703700',
    projectId: 'flex-market-cc177',
    storageBucket: 'flex-market-cc177.appspot.com',
    iosBundleId: 'com.example.flexmarket',
  );
}
